from enum import Enum


class SkillState(str, Enum):
    """Состояния навыка шахмат."""
    INITIATED = 'INITIATED'
    WAITING_CONFIRM = 'WAITING_CONFIRM'
    WAITING_COLOR = 'WAITING_COLOR'
    WAITING_MOVE = 'WAITING_MOVE'
    WAITING_DRAW_CONFIRM = 'WAITING_DRAW_CONFIRM'
    WAITING_RESIGN_CONFIRM = 'WAITING_RESIGN_CONFIRM'
    WAITING_NEWGAME_CONFIRM = 'WAITING_NEWGAME_CONFIRM'
    WAITING_SKILL_LEVEL = 'WAITING_SKILL_LEVEL'
    GAME_OVER = 'GAME_OVER'
