@startuml

autonumber
User -> Yandex_Dialogs: start_skill
Yandex_Dialogs -> alice_chess_skill: init_request()
alice_chess_skill -> alice_chess_skill: processRequest()
alice_chess_skill --> Yandex_Dialogs: SAY_YES
Yandex_Dialogs --> User: hi_text
User -> Yandex_Dialogs: request
Yandex_Dialogs -> alice_chess_skill: request + intents
alice_chess_skill -> alice_chess_skill: processRequest()
loop is_yes == True
    alt request.is_yes
    alice_chess_skill  --> Yandex_Dialogs: SAY_CHOOSE_COLOR
    Yandex_Dialogs --> User: SAY_CHOOSE_COLOR
    else 'request is not confirm'
    alice_chess_skill  --> Yandex_Dialogs: say_not_get_yes
    note right: 'repeat while not get confirmation'
    Yandex_Dialogs --> User: say_not_get_yes
    end
end

@enduml